# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.TextField(default='Studen name'),
            preserve_default=False,
        ),
    ]
