# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_group_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleRus', models.CharField(max_length=3, verbose_name='День недели')),
                ('titleEng', models.CharField(max_length=3, verbose_name='Day of week')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=15, verbose_name='Время')),
                ('pair', models.IntegerField(verbose_name='Номер пары')),
            ],
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Day', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pair', verbose_name='Пара'),
        ),
    ]
